user: root
port: 80
pid: /srv/webdata/http://servicespb.su/shared/thin.pid
log: /srv/webdata/http://servicespb.su/shared/log/thin.log
chdir: /srv/webdata/http://servicespb.su/current
environment: production
daemonize: false